import { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { Fade } from "react-awesome-reveal";
import { useSession } from "next-auth/react";

// COMPONENTS
import { Product, ProductProps } from "@/components/Product";
import { Footer } from "@/components/Footer";
import { Hero } from "@/components/Hero";
import { API } from "@/services/api";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState<ProductProps[]>([]);

  useEffect(() => {
    (async () => {
      const response = await API.get("/products");
      setProducts(response.data);
    })();

    console.log(
      "clientId: " + process.env.NEXT_PUBLIC_GOOGLE_CLIENT,
      "clientSecret: " + process.env.NEXT_PUBLIC_GOOGLE_KEY
    );
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Hero />
        <main className="flex justify-center py-4">
          <div className="container px-14">
            <h2 className="text-bold text-center text-2xl mb-6">Products</h2>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 gap-y-8 mb-10">
              <Fade cascade duration={400}>
                {products.map((product) => (
                  <Product product={product} key={product.id} />
                ))}
              </Fade>
            </div>
          </div>
        </main>

        <aside id="menu">{/* <Cart /> */}</aside>

        <Footer />
      </>
    </>
  );
}
