import { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";

// COMPONENTS
import { Product, ProductProps } from "@/components/Product";
import { Footer } from "@/components/Footer";
import { Hero } from "@/components/Hero";
import { API } from "@/services/api";

const inter = Inter({ subsets: ["latin"] });

// const products = [
//   {
//     id: "1",
//     name: "Product 1",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 20000,
//     imageURL: "/camera.jpg",
//   },
//   {
//     id: "2",
//     name: "Product 2",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 30000,
//     imageURL: "/mobile.jpg",
//   },
//   {
//     id: "3",
//     name: "Product 3",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 40050,
//     imageURL: "/headset.jpg",
//   },
//   {
//     id: "4",
//     name: "Product 4",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 45000,
//     imageURL: "/laptop.jpg",
//   },
//   {
//     id: "5",
//     name: "Product 5",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 50075,
//     imageURL: "/microfone.jpg",
//   },
//   {
//     id: "6",
//     name: "Product 6",
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto delectus excepturi nisi non necessitatibus" +
//       "officiis harum vero tenetur vel autem blanditiis quas expedita est ad, quod dolor. Suscipit, est doloribus?",
//     price: 100000,
//     imageURL: "/console.jpg",
//   },
// ];

export default function Home() {
  const [products, setProducts] = useState<ProductProps[]>([]);

  useEffect(() => {
    (async () => {
      const response = await API.get("/products");
      setProducts(response.data);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Hero />
        <main className="flex justify-center py-4">
          <div className="container px-14">
            <h2 className="text-bold text-center text-2xl mb-6">Products</h2>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 gap-y-8 mb-10">
              {products.map((product) => (
                <Product product={product} key={product.id} />
              ))}
            </div>
          </div>
        </main>

        <aside>{/* <Cart /> */}</aside>

        <Footer />
      </>
    </>
  );
}
